services:
  postgres_adventureworks:
    container_name: postgres_adventureworks
    image: wlcamargo/postgres-adventureworks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
    driver: local
